apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: {{ .Values.apiServer.image.repository  }}:{{ .Values.apiServer.image.tag }}
        ports:
        - containerPort: 3000
        env:  
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nestjs-backend-secrets
              key: MYSQL_ROOT_PASSWORD